- name: Install a docker packages
  apt:
    pkg:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    update_cache: yes
    state: present
  become: true

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present


- name: Install a  2rd docker packages
  apt:
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    update_cache: yes
    state: present
  become: true